//*********************************************************************************************
//
//          Web page
//
//*********************************************************************************************
            client.println("<!DOCTYPE html><html lang='pt-Br'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>Espectrofotometro</title><link rel='preconnect' href='https://fonts.googleapis.com'><link rel='preconnect' href='https://fonts.gstatic.com' crossorigin><link href='https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap' rel='stylesheet'></head>");
            client.println("<link rel='stylesheet' href='assets/css/main.min.css' />");
            client.println("<body data-estado='" + gpio2_state + "'>");
            client.println("<div class='container'>");
            client.println("<figure style='max-width: 40rem; height: auto;margin-bottom: 7rem;'><img style='width: 100%; height: auto;object-fit: contain;' src='https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaC3pAHSs0cw0QFjvWGdCjwZ3HTLsnHkXR6tB6-sxMDM0eHTaKsgfd35V0db3T8GwbZ1ab07Zs_raAEaZfXrWU3YG-k8zw=w2560-h955' alt='Especlux - Luminosidade a um passo de você!'><img style='width: 100%; height: auto;object-fit: contain;' src='https://lh3.googleusercontent.com/u/0/drive-viewer/AK7aPaBlOwprIS6WtTMtV878Rf-RjkvOgNe-nhAQDW7-rvXlfADKstZHczrn3WBn9jAy5e7J4Jq1Nlti9RkhU6VPO2mb4CWVYA=w2560-h955' alt='Especlux - Luminosidade a um passo de você!'></figure>");
            client.println("<h1 style='text-transform: uppercase;'>Espectrofotometro</h1>");
            client.println("<h2>Lâmpada - Estado: <span class='lampada' data-estado='" + gpio2_state + "'></span></h2><br>");
            client.println("<h2>Luminosidade: <span>" + lux + "</span><span> Lux</span></h2>");
            client.println("<div style='font-size: 2rem; display: flex; gap: 1rem; font-weight: 700;margin-top: 7rem;text-decoration: none;'><button data-interruptor='gpio2on'>Ligado</button> | <button data-interruptor='gpio2off'>Desligado</button></div>");
            client.println("<div style='position: absolute;left: 50%;top: 0;transform: translateX(-50%);width: 13.6rem;height: 13.6rem;'><style>.lamp1[data-estado='Ligado']{position: absolute;background: #fdb327;  box-shadow:  0 0 200px 50px #FFF,0 0 10px 1px #ff6600, 0 0 500px 100px #ffe066, 0 0 500px 250px #ffcc00, 0 0 200px 230px #ff6600, 0 0 10px 999px #000; transition: .1s;transition: .3s ease-in-out;}.lamp1[data-estado='Ligado'] ~.lamp2{ background: #fdb327; transition: .1s;}.lamp1[data-estado='Ligado'] ~ .resist-a{ background: #fff;box-shadow: 0 0 2rem 1px white;}.lamp1[data-estado='Ligado'] ~ .resist-b{ background: #fff;box-shadow: 0 0 2rem 3px white;  animation: fio 0.2s infinite;}</><style>.lamp1{position:absolute;width: 100px;height: 100px;background: grey;top: 10px; left: 50%;border-radius: 100% 95% 100% 30%;box-sizing: border-box;border-left: 0px solid #fdb327;  border-right: 0px solid #fdb327; transform: translateX(-50%) rotate(135deg);}</style><style>.lamp1-brilho::before{content:'';position:absolute;width: 27px;height: 60px;border-left: 10px solid rgba(255,255,255, .40);border-radius: 100%;margin: -5px 37px;   transform: rotate(100deg);}@media(max-width: 600px){.lamp1{width: 30px; height: 30px;}.lamp1-brilho::before{width: 7px;height: 3px;margin: 7px 15px;transform: rotate(-110deg);}}</style>");
            client.println("<div class='lamp1' data-estado='" + gpio2_state + "'><div class='lamp1-brilho'></div></div></div>");
            client.println("<script>document.querySelectorAll('button').forEach(function(e){e.addEventListener('click', function(){if(this.dataset.interruptor == 'gpio2on') {document.querySelectorAll('[data-estado]').forEach(function(e){e.dataset.estado = 'Ligado'})}if(this.dataset.interruptor == 'gpio2off') {document.querySelectorAll('[data-estado]').forEach(function(e){e.dataset.estado = 'Desligado'})}})})</script>");
            client.println("</body></html>");